// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mGQbfGwfQZiDDBnrzewypqBoyDDva7g',
    appId: '1:104681200877:android:3cf93499ab8c28f28bc0e4',
    messagingSenderId: '104681200877',
    projectId: 'fruits-hub-97ca6',
    storageBucket: 'fruits-hub-97ca6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_1s9KaRBQXVYG6Facjev3VNMHD5mB0k',
    appId: '1:104681200877:ios:5c55099932d980408bc0e4',
    messagingSenderId: '104681200877',
    projectId: 'fruits-hub-97ca6',
    storageBucket: 'fruits-hub-97ca6.firebasestorage.app',
    androidClientId: '104681200877-7u3hlohnv92sjrgf8cv891ppertqtjkv.apps.googleusercontent.com',
    iosClientId: '104681200877-l61bse0ivfdj685cnpjt4slp5hg6nebs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );
}
